### ISSUE TITLE
Konga crashes trying to take a snapshot

### ISSUE THREAD

**Issue by vicmonmena** [pantsel/konga#122]
Hi! Trying to take a snapshot, Konga crashes.

This is the error trace:

```
_http_outgoing.js:356
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.res.setHeader (/app/node_modules/@sailshq/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/app/node_modules/@sailshq/express/lib/response.js:595:10)
    at ServerResponse.res.json (/app/node_modules/@sailshq/express/lib/response.js:235:36)
    at ServerResponse.jsonx (/app/node_modules/sails/lib/hooks/responses/index.js:222:21)
    at Object.negotiate (/app/node_modules/sails/lib/hooks/responses/defaults/negotiate.js:39:38)
    at /app/api/controllers/SnapshotController.js:67:36
    at /app/node_modules/async/lib/async.js:721:13
    at /app/node_modules/async/lib/async.js:52:16
    at /app/node_modules/async/lib/async.js:264:21
    at /app/node_modules/async/lib/async.js:44:16
    at /app/node_modules/async/lib/async.js:718:17
    at /app/node_modules/async/lib/async.js:167:37
    at /app/api/controllers/SnapshotController.js:57:40
    at Request.handleRequestResponse [as _callback] (/app/node_modules/unirest/index.js:463:26)
    at Request.self.callback (/app/node_modules/unirest/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/app/node_modules/unirest/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/app/node_modules/unirest/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

More info:

- Kong version: 0.9.7
- Konga connection have 0.10.x defined

**Comment by jeremyjpj0916** [comment]
Straight from the homepage though : "Notice: Upgrade your Kong installations to v0.11.x so you can use Konga to it's full capacity. Support for older versions of Kong will be discontinued." Any reason you have stuck with such an outdated version?

**Comment by pantsel** [comment]
@vicmonmena, have you tried with the latest Konga and Kong versions?

**Comment by jeremyjpj0916** [comment]
Continuing onward with my review of Konga's latest deploy I now see Snapshots page is totally blank:

![snapshotsblank](https://user-images.githubusercontent.com/31913027/32483890-ce71a7d2-c36b-11e7-8471-68ece3856910.png)

This may be due to that migrations job I was showing you not fully seeding the db before that error when I think about it, but thought I would pass it along. All the other Konga functionality seems in place so far as I can tell but the snapshots page.

**Comment by jeremyjpj0916** [comment]
Update, even after cache refresh the snapshots page is still blank. Might be due to migrations not succeeding completely.

**Comment by jeremyjpj0916** [comment]
Update: Page is displaying properly for the automated Snapshots now, will further test today:

![snapshotsnew](https://user-images.githubusercontent.com/31913027/32629643-e0ee057e-c567-11e7-8c55-00736abbbf29.png)

**Comment by jeremyjpj0916** [comment]
Testing of the scheduled snapshot seems to work, I am not sure how Konga's internal Clock works. I guess it uses whatever the local server time is or UTC? I am currently in EST and I did configure it for 23:59 daily as pantsel recommended for a midnight snapshot(picture from above. The actual display of the snapshot is not saying it occured at 23:59 (see the 18:59), but I am pretty sure it did occur at the correct time for my timezone(11:59PM EST) which was what I actually wanted so maybe the saved time of snapshot taken is just displaying wrong at 18:59?:

![snapshotsupdate](https://user-images.githubusercontent.com/31913027/32645012-1b2ca9c0-c5b3-11e7-8f8b-0bb588a48386.png)

Lastly I will delete my two API's and their configurations and will install from snapshot now.

**Comment by jeremyjpj0916** [comment]
Findings from snapshot Restoration, it actually seemed to work as desired. Not sure why the picture and results are displaying as an error:

![restorationresults](https://user-images.githubusercontent.com/31913027/32645273-7123f13e-c5b4-11e7-9a6c-eff212c050e1.png)

To help Pantsel I am including a modified JSON here of my contents so he can replicate the error on his side, of course I modified the URL's and endpoints for privacy reasons:

```
{
	"createdUser": null,
	"updatedUser": null,
	"id": 2,
	"name": "snap@1510271940755",
	"kong_node_name": "UpdatedKong",
	"kong_node_url": "http://admin-kong-endpoint.com/",
	"kong_version": "0.11.1",
	"data": {
		"apis": [
			{
				"created_at": 1510042403797,
				"strip_uri": true,
				"id": "72de95c0-c2b6-4daf-9e3b-92fb65c3b92c",
				"name": "ApiNumberTwo",
				"http_if_terminated": false,
				"https_only": false,
				"retries": 5,
				"uris": [
					"/my/uri/two/here"
				],
				"upstream_url": "http://apinumbertwo.com",
				"upstream_send_timeout": 6000,
				"upstream_read_timeout": 6000,
				"upstream_connect_timeout": 6000,
				"preserve_host": false
			}, {
				"created_at": 1510043913963,
				"strip_uri": true,
				"id": "527d1a61-1832-4958-a47b-1875c69672d7",
				"name": "ApiNumberOne",
				"http_if_terminated": false,
				"https_only": false,
				"retries": 5,
				"uris": [
					"/my/uri/one/here"
				],
				"upstream_url": "https://apinumberone.com",
				"upstream_send_timeout": 6000,
				"upstream_read_timeout": 6000,
				"upstream_connect_timeout": 6000,
				"preserve_host": false
			}
		],
		"plugins": [
			{
				"created_at": 1510162452955,
				"config": {
					"whitelist": [
						"ApiNumberOne_Group"
					]
				},
				"id": "038aa76d-6454-4284-897b-19c542ced721",
				"enabled": true,
				"name": "acl",
				"api_id": "527d1a61-1832-4958-a47b-1875c69672d7"
			}, {
				"created_at": 1510162534365,
				"config": {
					"whitelist": [
						"ApiNumberTwo_Group"
					]
				},
				"id": "0b6c7768-64be-42fd-9fbe-410475a96e62",
				"enabled": true,
				"name": "acl",
				"api_id": "72de95c0-c2b6-4daf-9e3b-92fb65c3b92c"
			}, {
				"created_at": 1510162410586,
				"config": {
					"key_in_body": false,
					"run_on_preflight": true,
					"anonymous": "",
					"hide_credentials": false,
					"key_names": [
						"CompanyKey"
					]
				},
				"id": "30e689bf-be56-44f8-8cd0-d2b7a6e1c4a9",
				"enabled": true,
				"name": "key-auth",
				"api_id": "527d1a61-1832-4958-a47b-1875c69672d7"
			}, {
				"created_at": 1510162510944,
				"config": {
					"key_in_body": false,
					"key_names": [
						"CompanyKey"
					],
					"anonymous": "",
					"run_on_preflight": true,
					"hide_credentials": false
				},
				"id": "acf19adf-8650-4ac6-8d14-bcd8aefd2771",
				"enabled": true,
				"name": "key-auth",
				"api_id": "72de95c0-c2b6-4daf-9e3b-92fb65c3b92c"
			}
		],
		"consumers": [
			{
				"custom_id": "test",
				"created_at": 1510042422583,
				"username": "test",
				"id": "0b708315-070f-42e7-8212-b3db98bf4e12",
				"acls": [
					{
						"group": "ApiNumberTwo_Group",
						"created_at": 1510162637021,
						"id": "1217a79c-3e27-4dff-bb06-13a4543ac780",
						"consumer_id": "0b708315-070f-42e7-8212-b3db98bf4e12"
					}, {
						"group": "ApiNumberOne_Group",
						"created_at": 1510162651156,
						"id": "dece2938-c006-4bf1-b052-0cfe07b91442",
						"consumer_id": "0b708315-070f-42e7-8212-b3db98bf4e12"
					}
				],
				"credentials": {
					"basic-auth": [],
					"key-auth": [
						{
							"id": "225f6cb2-1d91-4512-b01f-94baed4466d4",
							"created_at": 1510162603728,
							"key": "OwbHactz8piN4ZBi5E4PhQaJ0AQw0bpa",
							"consumer_id": "0b708315-070f-42e7-8212-b3db98bf4e12"
						}
					],
					"hmac-auth": [],
					"jwt": [],
					"oauth2": []
				}
			}
		],
		"upstreams": []
	},
	"createdAt": "2017-11-09T23:59:00.000Z",
	"updatedAt": "2017-11-09T23:59:00.000Z"
}
```

To explain what the above json represents in simple terms:
1. Two API's protected with ACL and Key-Auth.
2. One consumer with the proper ACL whitelist groups assigned to call the above API's. He also has 1 Key-Auth generated for his account which will let him call the above API's.

Not exactly sure why Konga thought its restoration was an error? Potentially because it was one Key-Auth that needed to be setup that gave access to two API's and it tried adding it twice? Not sure will let Pantsel investigate if he likes. The restoration worked wonders I think :) ! Amazing feature and I hope it scales to larger test sizes later with no issues.

**Comment by fergyfresh** [comment]
I can create services with konga just fine and create routes, but I'm trying to save my progress with a snapshot and this is what happens, both with instant snapshots and scheduled snapshots:

```
kong-database_1      | ERROR:  syntax error at or near ")" at character 627
kong-database_1      | STATEMENT:  SELECT "konga_kong_upstream_alerts"."id", "konga_kong_upstream_alerts"."upstream_id", "konga_kong_upstream_alerts"."email", "konga_kong_upstream_alerts"."slack", "konga_kong_upstream_alerts"."cron", "konga_kong_upstream_alerts"."active", "konga_kong_upstream_alerts"."data", "konga_kong_upstream_alerts"."createdAt", "konga_kong_upstream_alerts"."updatedAt", "konga_kong_upstream_alerts"."createdUserId", "konga_kong_upstream_alerts"."updatedUserId", "konga_kong_upstream_alerts"."connection" FROM "public"."konga_kong_upstream_alerts" AS "konga_kong_upstream_alerts"  WHERE "konga_kong_upstream_alerts"."upstream_id" NOT IN ()  
konga_1              | KongProxyHooks:upstreams:afterList:Failed to find orphaned upstreams Error (E_UNKNOWN) :: Encountered an unexpected error
konga_1              | error: syntax error at or near ")"
konga_1              |     at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
konga_1              |     at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
konga_1              |     at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
konga_1              |     at emitOne (events.js:116:13)
konga_1              |     at Socket.emit (events.js:211:7)
konga_1              |     at addChunk (_stream_readable.js:263:12)
konga_1              |     at readableAddChunk (_stream_readable.js:250:11)
konga_1              |     at Socket.Readable.push (_stream_readable.js:208:10)
konga_1              |     at TCP.onread (net.js:601:20)
konga_1              | 
konga_1              | Details:  error: syntax error at or near ")"
konga_1              | 
konga_1              | (node:8) UnhandledPromiseRejectionWarning: Error (E_UNKNOWN) :: Encountered an unexpected error
konga_1              | error: syntax error at or near ")"
konga_1              |     at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
konga_1              |     at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
konga_1              |     at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
konga_1              |     at emitOne (events.js:116:13)
konga_1              |     at Socket.emit (events.js:211:7)
konga_1              |     at addChunk (_stream_readable.js:263:12)
konga_1              |     at readableAddChunk (_stream_readable.js:250:11)
konga_1              |     at Socket.Readable.push (_stream_readable.js:208:10)
konga_1              |     at TCP.onread (net.js:601:20)
konga_1              | (node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by fergyfresh** [comment]
This is what my docker-compose.yml file looks like:

```
version: "3"

networks:
 kong-net:
  driver: bridge

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:latest
    command: "kong migrations up"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: always
    networks:
      - kong-net
    environment:
      KONG_PG_HOST: kong-database
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong@kong-database:5432/konga_db"
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    restart: always
    networks:
        - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      DB_DATABASE: konga_db
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"
```
