### ISSUE TITLE
Using Kong to expose Konga

### ISSUE THREAD

**Issue by rmetcalf9** [pantsel/konga#157]
I am new to kong, Konga and Docker stacks. I have build a docker-compose file which will run kong and konga. In the Konga service I have exposed post 1337 and it is working without any issue. I can log in to Konga, connect it to kong and preform operations.

I had what I thought was a clever idea and I decided to expose Konga via Kong. I just added an API
(part of the raw view)

```
  "created_at": 1515856518917,
  "strip_uri": true,
  "id": "fb66facc-78d3-4b97-a577-2f0a006c8b45",
  "name": "konga",
  "http_if_terminated": false,
  "https_only": false,
  "upstream_url": "http://konga:1337",
  "uris": [
    "/konga"
  ],
  "preserve_host": false,
  "upstream_connect_timeout": 60000,
```
I can now go to http://mypublicdockerstack:80/konga/ I get the kong log in. I have been able to do this both through http and https.
However - I have a rather confusing issue. If I go to connections and get konga to connect to kong I get the message "Oh snap! Can't connect to http://kong:8001" This works for both http and https.

If I switch to the directly exposed kong port it works without a problem.

I can't understand why the method I use to connect to konga is affecting the connection between konga and kong. Again I am a beginner so I am probably missing something simple.

The docker file I am using is:
````
#SOADevTeamServer docker compose file to setup services behind kong API gateway
#Based on https://github.com/Kong/docker-kong/blob/master/compose/docker-compose.yml
# see also https://github.com/Kong/kong

version: "3.1"

secrets:
  webservices_hostname:
    external: true
  webservices_cert:
    external: true
  webservices_key:
    external: true

services:

#Create a new empty database for kong to use
# postgress used instead of cassendra as I haven't been able to find a healthcheck command for cassendra
  kong-database:
    image: postgres:9.4
    deploy:
      restart_policy:
        condition: any
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

#Setup kong database
  kong-migration:
    image: kong
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up
    deploy:
      restart_policy:
        condition: on-failure

#Start the kong server
  kong:
    image: kong
    deploy:
      restart_policy:
        condition: any
    secrets:
     - webservices_cert
     - webservices_key
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_SSL_CERT=/run/secrets/webservices_cert
      - KONG_SSL_CERT_KEY=/run/secrets/webservices_key
    ports:
      - 80:8000
      - 443:8443
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
    restart: on-failure

#The next section starts a UI for kong called konga. 
#We only need a ui for development experimentation and can be removed if no UI is required
# when it is running it can be accessed on port 1337
  konga:
    image: pantsel/konga
    deploy:
      restart_policy:
        condition: on-failure
    ports:
     - 1337:1337

#Configure kong to forward requests to flaskapp
  kong-addapis-konga:
    image: byrnedo/alpine-curl
    deploy:
      restart_policy:
        condition: on-failure
    command: "-i -X POST \
                --url http://kong:8001/apis/ \
                --data 'name=flaskapp' \
                --data 'uris=/flaskapp' \
                --data 'upstream_url=http://flaskapp:80'
                --data 'https_only=true'
             "
````

The command I use to start the docker stack is:
````
docker stack deploy --compose-file ./docker-compose.yml webservices
````

Thanks in advance for any advice.
