### ISSUE TITLE
http://localhost:1337/kong gives Failed to load resource: the server responded with a status of 400 (Bad Request)

### ISSUE THREAD

**Issue by mateodelnorte** [pantsel/konga#184]
Hi there,

I'm getting up and running using docker, kong, and konga. I'm unable to create a connection (clicking the button does nothing, after providing field data). Nothing logged to the console, but it does show this: 

![image](https://user-images.githubusercontent.com/554847/37006392-c0cd09ac-209d-11e8-8ece-ee48de76fc8c.png)

Here is my docker-compose file: 
```
version: '2.1'

services:

  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8500 || exit 1"]
      interval: 5s
      retries: 10
    networks:
      - kong
    ports:
      - 8500:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
      - 127.0.0.1

  nginx-lb:
    build: nginx/
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - kong
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    expose:
      - 8000
      - 8443
      - 8001
      - 8444
    links:
      - consul:consul
    command: >
        /bin/containerpilot
        -config file:///etc/containerpilot/containerpilot.json
        nginx -g "daemon off;"

  kong-database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    networks:
      - kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  kong-migration:
    image: kong
    depends_on:
      kong-database:
        condition: service_healthy
    networks:
      - kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up

  kong:
    build: kong/
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001        
    networks:
      - kong
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10

  konga:
    image: pantsel/konga
    depends_on:
      kong-database:
        condition: service_healthy
    environment: 
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_PORT=5432
      - DB_USER=kong
      # - DB_PASSWORD=your-db-password" \ // Omit if not relevant
      - DB_DATABASE=kong
      - NODE_ENV=development    
    networks:
      - kong
    expose: 
      - 1337
    ports:
      - 1337:1337

networks:

  kong:
    # external: true
```

Any ideas what might be happening? 

Thanks for what looks like a very cool project.
