### ISSUE TITLE
Prepare the database error

### ISSUE THREAD

**Issue by linydquantil** [pantsel/konga#305]
my yaml job for prepare konga:
```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: konga-migrate
spec:
  template:
    metadata:
      labels:
        app: konga-migrate
    spec:
      containers:
        - name: konga
          image: pantsel/konga:next
          imagePullPolicy: Always
          args:
            - "-c prepare"
            - "-a mysql"
            - "-u mysql://konga:konga@hostname:3306/konga"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
      restartPolicy: Never
```

but i found the log is  Invalid command:  prepare;
so how to resolve this error?

**Comment by pantsel** [comment]
@linydquantil try this way,

```
 #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a mysql -u mysql://konga:konga@hostname:3306/konga"
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database
```
