### ISSUE TITLE
PostgreSQL adapter not working

### ISSUE THREAD

**Issue by smazurov** [pantsel/konga#35]
Latest version that introduced some real persistence (thanks for that, by the way!) doesn't seem to be fully working:

```
kong-ui-db_1  | ERROR:  relation "public.konga_users" does not exist at character 46
kong-ui-db_1  | STATEMENT:  SELECT COUNT(*) as count FROM (SELECT * FROM "public"."konga_users" ) AS "konga_users"
ui_1          | User had models, so no seed needed
ui_1          | A hook (`load-db`) failed to load!
ui_1          | Error (E_UNKNOWN) :: Encountered an unexpected error
ui_1          | error: relation "public.konga_users" does not exist
ui_1          |     at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
ui_1          |     at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
ui_1          |     at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
ui_1          |     at emitOne (events.js:96:13)
ui_1          |     at Socket.emit (events.js:191:7)
ui_1          |     at readableAddChunk (_stream_readable.js:176:18)
ui_1          |     at Socket.Readable.push (_stream_readable.js:134:10)
ui_1          |     at TCP.onread (net.js:563:20)
ui_1          |
ui_1          | Details:  error: relation "public.konga_users" does not exist
ui_1          |
```

A quick `docker-compose.yml` that demonstrates this problem:

```yml
version: '2'
services:
  kong-ui-db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong-ui
      - POSTGRES_DB=kong-ui
      - POSTGRES_PASSWORD=testtest123
  ui:
    image: pantsel/konga:latest
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=db
      - DB_USER=kong-ui
      - DB_PASSWORD=testtest123
      - DB_DATABASE=kong-ui
    links:
      - kong-ui-db:db
```
