### ISSUE TITLE
Relative paths / base url

### ISSUE THREAD

**Issue by robertofabrizi** [pantsel/konga#357]
Hello everyone, I've read around that Konga supports setting a base path to use in combination with a reverse proxy like Traefik, something like BASE_URL=/konga.

In the list of the supported env variables there is no trace of anything like it.

Thank you,
Roberto

**Comment by pantsel** [comment]
@robertofabrizi , Konga should work out of the box in a reverse proxy configuration without the need to define a base path.

The `/konga` path should be defined on the proxy itself.

Nginx example:
```
server {
    listen       80;
    server_name www.example.com;
    location /konga {
        proxy_pass      http://konga.host:1337;
        proxy_set_header Host            $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

A Traefik example would be something like this (untested):
```
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
       url = "konga.host:1337"

[frontends]
  [frontends.frontend1]
      backend = "backend1"
      passHostHeader = true
      [frontends.frontend1.routes.example]
          rule = "Host:example.com;PathPrefix:/konga;ReplacePathRegex:^/konga(.*) /backend1$$1"
```

**Comment by robertofabrizi** [comment]
@pantsel I've not tested it because whenever I tried that with other tools (sonarqube, gogs, nexus, swarmpit...) they would load some of the main page, but the URLs of the CSS and JS inside the main page wouldn't contain the "/konga" token and therefore wouldn't be routed by the reverse proxy to the proper backend, they all required to define a base relative path so that all the page dependencies and ajax calls would be properly routed. Konga doesn't need that?

**Comment by pantsel** [comment]
@robertofabrizi , no.

According to my tests at least, I've been able to run Konga with no probs in a reverse proxy config.

You could try it as well and provide some feedback.

I would be glad to help out.

**Comment by robertofabrizi** [comment]
I think that I got the result that I was expecting:

          - "traefik.frontend.rule=PathPrefix:/konga;ReplacePathRegex:^/konga(.*) /$$1"

The homepage is found because I looked it up using host:port/konga, but all other dependencies inside it are not found because they aren't searched with a url starting with /konga, therefore the rule above doesn't apply:

![image](https://user-images.githubusercontent.com/6720929/54625458-a1ed0080-4a6f-11e9-8d4b-dc5c284b2e8a.png)

**Comment by pantsel** [comment]
I'll try something out and keep you posted.

**Comment by robertofabrizi** [comment]
Amazing thank you very much

**Comment by pantsel** [comment]
@robertofabrizi , sorry for the late response.

I just had some time to test things out.

I have it working with nginx and apache but still trying to figure out the proper traefic configuration.

In the meantime, to make things easier, I applied the `BASE_URL` logic on the [next](https://github.com/pantsel/konga/tree/next) branch.

It is also available from docker hub via `pantsel/konga:next`.

That branch holds the edge features and changes that will be introduced in the upcoming release.

Check out the new env variables in the [README](https://github.com/pantsel/konga/blob/next/README.md) and feel free to try it out and give me some feedback.

Cheers.

**Comment by robertofabrizi** [comment]
Your support is amazing, I wish that more projects had such incredible devs.
Sadly I must be doing something wrong, this is what I've tried:

`    konga:
      image: pantsel/konga:next
      environment:
        BASE_URL: konga
      ports:
        - "1337:1337"
      networks:
        - sytel-devops-overlay-network
      deploy:
        labels:
          - traefik.backend=konga
          - traefik.port=1337
          - "traefik.frontend.rule=PathPrefix:/konga"
          #- "traefik.frontend.rule=PathPrefix:/konga;ReplacePathRegex:^/konga(.*) /$$1"
          - traefik.frontend.passHostHeader=true
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure
`

Even ignoring for a second the Traefix overlay complexity, I was expecting to see konga going to http://10.46.90.125:1337/konga, but I get a 404.

I've also tried setting BASE_URL: /konga but the end result was the same.

Am I missing something?

Thank you!

**Comment by pantsel** [comment]
@robertofabrizi ,

try this:
```
konga:
  image: pantsel/konga:next
  environment:
    BASE_URL: /konga/
  ports:
    - "1337:1337"
  networks:
    - sytel-devops-overlay-network
  deploy:
    labels:
      - traefik.backend=konga
      - traefik.port=1337
      - traefik.frontend.rule=PathPrefixStrip:/konga
      - traefik.frontend.passHostHeader=true
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
```

**Comment by robertofabrizi** [comment]
Works like a charm that way!

**Comment by pantsel** [comment]
Great!

The new release is scheduled to come out soon. So stay on `:next` until then. Everything should be working (logically).

Keep an eye on Konga's releases so that you change your instance to use the upcoming release.

**Comment by robertofabrizi** [comment]
Top! Thank you so much for the prompt help and addition!

**Comment by amolsh** [comment]
@pantsel  I want to access konga dashboard via kubernetes ingress on "/konga" path. 
So, where should i put these labels as putting them in label field won't work.

      - traefik.backend=konga
      - traefik.port=1337
      - traefik.frontend.rule=PathPrefixStrip:/konga
      - traefik.frontend.passHostHeader=true
 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-dashboard
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-dashboard
  template:
    metadata:
      labels:
        name: kong-dashboard
        app: kong-dashboard
    spec:
      containers:
        - name: kong-dashboard
          image: pantsel/konga:next
          ports:
            - name: main
              containerPort: 1337
              protocol: TCP
          env:
            - name: TOKEN_SECRET
              value: "random-string"
            - name: DB_ADAPTER
              value: "postgres"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "kong"
            - name: DB_PASSWORD
              value: "kong"
            - name: DB_DATABASE
              value: "kong"
            - name: BASE_URL
              value: "/konga/"

```
