### ISSUE TITLE
Konga container keeps dying

### ISSUE THREAD

**Issue by DigitalTargit** [pantsel/konga#405]
docker logs    aim_konga.1.n1el61rzwkof09354slbsslc9                                                                                                                                                                 events.js:183                                                                                                                                                                                                                                       throw er; // Unhandled 'error' event                                                                                                                                                                                                          ^                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Error: read ECONNRESET                                                                                                                                                                                                                            at TLSWrap.onread (net.js:622:25)
--


db is postgress

**Comment by DigitalTargit** [comment]
is there another service log I can try to obtain for you ?

**Comment by swapnild2111** [comment]
Please help me fix this....
Unable to connect to SSL enabled postgres database

```
env:
        - name: KONGA_LOG_LEVEL
          value: "debug"
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "xxx.postgres.database.azure.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "xxx@postgres"
        - name: DB_PASSWORD
          value: "yyy"
        - name: DB_DATABASE
          value: "konga_database"
        - name: DB_POOLSIZE
          value: "10"
        - name: DB_SSL
          value: "true"
        - name: DB_ADAPTER
          value: "postgres"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
```

And logs of konga pod after k8s deployment
```
Hook:api_health_checks:process() called
Hook:health_checks:process() called
Hook:start-scheduled-snapshots:process() called
Hook:upstream_health_checks:process() called
Hook:user_events_hook:process() called
User had models, so no seed needed
Start scheduled health checks for node 1
Kongnode had models, so no seed needed
Emailtransport seeds updated
Performing health check for node 1
Health check for node 1 succeeded { database: { reachable: true },
  memory:
   { workers_lua_vms:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     lua_shared_dicts:
      { kong_locks: [Object],
        kong: [Object],
        kong_process_events: [Object],
        kong_db_cache: [Object],
        kong_cluster_events: [Object],
        kong_db_cache_miss: [Object],
        prometheus_metrics: [Object],
        kong_healthchecks: [Object],
        kong_rate_limiting_counters: [Object] } },
  server:
   { connections_writing: 1,
     total_requests: 181602,
     connections_handled: 17547,
     connections_accepted: 17547,
     connections_reading: 0,
     connections_active: 2,
     connections_waiting: 1 } }
KongNode:afterUpdate:called()
KongNode:afterUpdate:health_checks true
KongNode:afterUpdate:emit health_checks.start
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25)
```
