### ISSUE TITLE
Konga crashes after some period of time

### ISSUE THREAD

**Issue by TeddyDD** [pantsel/konga#410]
Konga: v0.14.1
Kong: v1.1.1
Node: 10.16.0 / 8.16.0 / 8.11..3

Konga crashes after some period of time. It's most likely related to user activity (we tried to run Konga for ~1h without using an UI and there was no crash).  It's hard to tell what triggers the crash. 

We thought [this](https://github.com/nodejs/node/issues/23169) issue can be related but using node 8.x does not solve the issue. [This SO question](https://stackoverflow.com/questions/54037384/nodejs-error-read-econnreset-at-tcp-onstreamread-internal-stream-base-common) can be related to `onStreamRead` error.

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kongadmin@0.14.1 start: `node --harmony app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kongadmin@0.14.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/centos/.npm/_logs/2019-07-05T10_33_29_219Z-debug.log
```

and

```
debug: KongProxyController:entity null
debug: Kong admin url => https://localhost:28444
debug: KongProxyHooks:afterEntityList called() status
debug: KongProxyHooks:afterEntityFetch called() null
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by TeddyDD** [comment]
It seems that incorrectly configured proxy causes this issue. It shoudn't result in crash tho.

**Comment by swapnild2111** [comment]
Please help me fix this....
Unable to connect to SSL enabled postgres database

```
env:
        - name: KONGA_LOG_LEVEL
          value: "debug"
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "xxx.postgres.database.azure.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "xxx@postgres"
        - name: DB_PASSWORD
          value: "yyy"
        - name: DB_DATABASE
          value: "konga_database"
        - name: DB_POOLSIZE
          value: "10"
        - name: DB_SSL
          value: "true"
        - name: DB_ADAPTER
          value: "postgres"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
```

And logs of konga pod after k8s deployment
```
Hook:api_health_checks:process() called
Hook:health_checks:process() called
Hook:start-scheduled-snapshots:process() called
Hook:upstream_health_checks:process() called
Hook:user_events_hook:process() called
User had models, so no seed needed
Start scheduled health checks for node 1
Kongnode had models, so no seed needed
Emailtransport seeds updated
Performing health check for node 1
Health check for node 1 succeeded { database: { reachable: true },
  memory:
   { workers_lua_vms:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     lua_shared_dicts:
      { kong_locks: [Object],
        kong: [Object],
        kong_process_events: [Object],
        kong_db_cache: [Object],
        kong_cluster_events: [Object],
        kong_db_cache_miss: [Object],
        prometheus_metrics: [Object],
        kong_healthchecks: [Object],
        kong_rate_limiting_counters: [Object] } },
  server:
   { connections_writing: 1,
     total_requests: 181602,
     connections_handled: 17547,
     connections_accepted: 17547,
     connections_reading: 0,
     connections_active: 2,
     connections_waiting: 1 } }
KongNode:afterUpdate:called()
KongNode:afterUpdate:health_checks true
KongNode:afterUpdate:emit health_checks.start
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25)
```
