### ISSUE TITLE
Konga redirects to /register instead of /konga/register

### ISSUE THREAD

**Issue by reloaded** [pantsel/konga#435]
This issue a bug related to #357.

The goal is to host Konga at `/konga`, but  Konga redirects to `/register` instead of `/konga/register`. I've not customized any configuration for Kong or  Konga so both their database configurations are vanilla.

This seems to be a bug that only impacts the `HTTP 302 /register` redirect when opening Konga on a clean, out of the box install. The developer tools show all Konga requests are going to `/konga/` except for the `HTTP 302 /register` redirect.

I tried accessing Konga two different ways. The first is through ingress and the second is bypassing ingress and using `kubectl port-forward`.

### First attempt, through the Ingress

![image](https://user-images.githubusercontent.com/1775239/63198691-53e52480-c030-11e9-9077-86c66c8c3a09.png)

![image](https://user-images.githubusercontent.com/1775239/63198723-6d866c00-c030-11e9-8018-3d16d5de4656.png)

As shown above, Konga sends a `HTTP 320 /register` to the browser when access my ingress at `/konga`.

![image](https://user-images.githubusercontent.com/1775239/63198737-7d9e4b80-c030-11e9-8bf6-39208d214475.png)

### Second attempt, bypassing ingress with kubectl port-forward

To rule out Ingress configuration issues I thought it was a good idea to access Konga directly without involving Kong or k8s Ingress. This revealed Konga is redirecting everything to `/konga/` except for the `HTTP 302 /register` redirect.

First I establish a direct connection to the Konga pod.

![image](https://user-images.githubusercontent.com/1775239/63198541-e76a2580-c02f-11e9-9c7f-b0193ecb2dc1.png)

Then I accessed Konga directly and as seen below Konga successfully loads `/register`. This is expected because I'm bypassing my ingress. Keep in mind I left Konga's BASE_URL environment variable set to `/konga/` in my deployment file.

![image](https://user-images.githubusercontent.com/1775239/63198584-05d02100-c030-11e9-8bf4-52920a14debe.png)

Here is where the bug rears it's ugly head. The web page  rendered incorrectly and I immediately knew web assets were not loaded. Sure enough all web assets 404'd except for the `/register` page itself.

![image](https://user-images.githubusercontent.com/1775239/63198598-12547980-c030-11e9-9ae8-0c64063677d3.png)

Here's my YAML configuration.
```

# Source: konga/templates/konga.svc.yaml
kind: Service
apiVersion: v1
metadata:
  name: "konga-konga-svc"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 1337
  selector:
    app: "konga-konga"
    release: "konga"
    chart: "konga-0.1.0"
  type: ClusterIP
---
# Source: konga/templates/konga.deploy.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "konga-konga"
  labels:
    app: "konga-konga"
    release: "konga"
    chart: "konga-0.1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "konga-konga"
      release: "konga"
      chart: "konga-0.1.0"
  template:
    metadata:
      labels:
        app: "konga-konga"
        release: "konga"
        chart: "konga-0.1.0"
    spec:
      imagePullSecrets:
        []

      containers:
      - name: konga
        image: "pantsel/konga:next"
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 1337
            protocol: TCP
        resources:
            {}
            
        env:
          
            - name: NODE_ENV
              value: development
            - name: TOKEN_SECRET
              value: 9GbbT5Oa2XaH
            - name: BASE_URL
              value: /konga/
---
# Source: konga/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "konga-konga-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  
  - http:
      paths:
      - path: /konga
        backend:
          serviceName: "konga-konga-svc"
          servicePort: 80

```

**Comment by pantsel** [comment]
@reloaded , The current version of Konga doesn't play well with relative paths.
You can instead try the `next` branch or `pantsel/konga:next` from docker hub.

Check out the changelog
https://github.com/pantsel/konga/blob/next/CHANGELOG.md

I think that's what you need.

**Comment by reloaded** [comment]
> @reloaded , The current version of Konga doesn't play well with relative paths.
> You can instead try the `next` branch or `pantsel/konga:next` from docker hub.
> 
> Check out the changelog
> https://github.com/pantsel/konga/blob/next/CHANGELOG.md
> 
> I think that's what you need.

You overlooked my kubernetes manifest definitions at the end of the post. I am already referencing "pantsel/konga:next". 

This bug is in the "next" branch.

**Comment by pantsel** [comment]
You're right. Let me see what I can do.

**Comment by reloaded** [comment]
Thank you for the superb support @pantsel

**Comment by reloaded** [comment]
@pantsel  this still seems to be an issue. I'm referencing `pantsel/konga:next` and setting the BASE_URL environment variable to `/konga/` but it's still redirecting me to `/register` for a new Konga instance without prior Konga configurations.

**Comment by reloaded** [comment]
`kubectl describe pod kops-konga-deploy-6ccc6dd86c-m2dkj` 

```
Name:           kops-konga-deploy-6ccc6dd86c-m2dkj
Namespace:      etl
Priority:       0
Node:           bmk8ngpunode/10.251.96.21
Start Time:     Fri, 06 Sep 2019 10:39:35 -0700
Labels:         app.kubernetes.io/instance=kops-konga
                app.kubernetes.io/name=kops-konga
                pod-template-hash=6ccc6dd86c
Annotations:    <none>
Status:         Running
IP:             10.32.0.9
Controlled By:  ReplicaSet/kops-konga-deploy-6ccc6dd86c
Containers:
  konga:
    Container ID:   docker://a2144579b1bee5a684aa61b46c3e2d692f6f2701687f08bbbd17efdd78a70076
    Image:          pantsel/konga:next
    Image ID:       docker-pullable://pantsel/konga@sha256:a064b58e44f755acd0bba3bbef068d9edf6af9b5461d336ce00bdb26d35a77d5
    Port:           1337/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 06 Sep 2019 10:41:18 -0700
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 06 Sep 2019 10:40:26 -0700
      Finished:     Fri, 06 Sep 2019 10:40:26 -0700
    Ready:          True
    Restart Count:  4
    Environment:
      DB_ADAPTER:    <set to the key 'db-adapter' in secret 'kops-konga-secrets'>    Optional: false
      DB_HOST:       <set to the key 'db-host' in secret 'kops-konga-secrets'>       Optional: false
      DB_PORT:       <set to the key 'db-port' in secret 'kops-konga-secrets'>       Optional: false
      DB_USER:       <set to the key 'db-username' in secret 'kops-konga-secrets'>   Optional: false
      DB_PASSWORD:   <set to the key 'db-password' in secret 'kops-konga-secrets'>   Optional: false
      BASE_URL:      <set to the key 'base-url' in secret 'kops-konga-secrets'>      Optional: false
      NODE_ENV:      <set to the key 'node-env' in secret 'kops-konga-secrets'>      Optional: false
      TOKEN_SECRET:  <set to the key 'token-secret' in secret 'kops-konga-secrets'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-p26z6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-p26z6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-p26z6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                   Message
  ----     ------     ----                  ----                   -------
  Normal   Scheduled  5m8s                  default-scheduler      Successfully assigned etl/kops-konga-deploy-6ccc6dd86c-m2dkj to bmk8ngpunode
  Normal   Pulling    4m18s (x4 over 5m7s)  kubelet, bmk8ngpunode  Pulling image "pantsel/konga:next"
  Normal   Pulled     4m18s (x4 over 5m6s)  kubelet, bmk8ngpunode  Successfully pulled image "pantsel/konga:next"
  Normal   Created    4m18s (x4 over 5m6s)  kubelet, bmk8ngpunode  Created container konga
  Normal   Started    4m17s (x4 over 5m5s)  kubelet, bmk8ngpunode  Started container konga
  Warning  BackOff    3m37s (x9 over 5m)    kubelet, bmk8ngpunode  Back-off restarting failed container

```

Pod Environment Variables:
```
BASE_URL=/konga/
DB_PORT=5432
DB_HOST=postgresql-postgresql
HOSTNAME=kops-konga-deploy-6ccc6dd86c-m2dkj
DB_USER=postgres
NODE_ENV=development
DB_PASSWORD=xxxx
DB_ADAPTER=postgres
TOKEN_SECRET=xxxxx
```

**Comment by reloaded** [comment]
@pantsel  Is this related to the fact that the `:next` docker image hasn't been updated in months even after your recent `BASE_URL` bug patch?

![image](https://user-images.githubusercontent.com/1775239/64471206-602a4200-d103-11e9-96f0-8c05a1c389fc.png)

**Comment by reloaded** [comment]
@pantsel  any movement on this issue?

**Comment by pantsel** [comment]
@reloaded , I'm terribly sorry for the delayed response.

The branch wasn't updated due to a change on github's integration with 3rd party platforms.

That is something I recently noticed as well.

Anyway, the integration with dockerhub is working again and a new release is out, that includes all fixes and updates from the `next` branch.

**Comment by alvindaiyan** [comment]
Hi, I think the issue still exist

**Comment by fgsalomon** [comment]
Hi @pantsel.

I think that @alvindaiyan is right and this issue is still not fixed.

I've tried the Docker images with tags `0.14.7`, `next` and `latest` and none of them worked. They all give a 404 error code when using `BASE_URL` env variable.

**Comment by Diegoescalonaro** [comment]
Any update about that? I don't be able to expose all the Konga's static files through Kong's route. I suppose the BASE_URL would solve that problem.

**Comment by btkelly** [comment]
Any update on this? I'm experiencing the same issues.

**Comment by wangfeng-1** [comment]
Any update on this? I'm experiencing the same issues.

**Comment by chenguang-Steve** [comment]
Same issue for me.

**Comment by jack-gringo** [comment]
Im using Kubernates/Nginx

did this below from [this](https://stackoverflow.com/a/65725055) answer and it worked!

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kong
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress-nginx-kong
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /konga(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: konga-service
                port:
                  name: konga-proxy
```
