### ISSUE TITLE
Cannot create a connection to the kong:1.3 running in k8s

### ISSUE THREAD

**Issue by crixo** [pantsel/konga#517]
I have kong1.3 running in k8s using kong-ingress-controller.
I deployed pantsel/konga:0.14.7 in k8s as well exposing a service(ClusterIP) to reach it via port-forwarding.

I create also service(ClusterIP) to expose kong api (in version 1.3 admin api are no longer expose by default via service). 
```
apiVersion: v1
kind: Service
metadata:
  name: kong-admin-api
  namespace: kong
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8444
    protocol: TCP
  selector:
    app: ingress-kong
````
Through the new service I'm able to connect me locally (https://localhost:8002/) via port-forwarding.
```
kubectl port-forward -n kong svc/kong-admin-api 8002:8001
```

I'm expecting to connect the konga ui to the new service providing the following url as KONG ADMIN URL
https://kong-admin-api:8001
but I'm getting "Connection refused" same as running the same url from konga pod via curl
What am i missing?
