### ISSUE TITLE
Kong 2.0 Compatibility

### ISSUE THREAD

**Issue by thangaraja** [pantsel/konga#533]
Kong 2.0 is released. Has anyone tested? Any known issues?  Any update on when Konga will officially support Kong 2.0?

**Comment by gettoarun** [comment]
Doesn't work. Fails with HTTP 500/Internal Server Error and only an empty error object. 

{"error":{}}

**Comment by larsnaesbye** [comment]
That's weird. We're running Kong 2.0.0 and the latest Konga... ![Kong 2.0.0 and the latest Konga](https://user-images.githubusercontent.com/7767079/75351791-fe27e980-58a8-11ea-8953-70672fa94e4e.jpg)

**Comment by larsnaesbye** [comment]
But I suppose the Konga 2 repo is a WIP thing specifically for Kong 2?

**Comment by uleodolter** [comment]
I have kong 2.0.1 and 0.14.7 running, seems to work, maybe not all kong features are implemented but works for my configuration.

**Comment by jschirrmacher** [comment]
Works here (Kong 2.0.1 and Konga 0.14.7) as well, but doesn't offer all Plugins available in Kong, e.g. the [ACME plugin](https://docs.konghq.com/hub/kong-inc/acme/), which would be extremely helpful.

**Comment by larsnaesbye** [comment]
Have any of you tried Konga 2?

**Comment by javaChip56** [comment]
Not sure if the question is specifically asking for 2.0, but I have Konga 0.14.7 and Kong 2.0.1 running in Docker containers. Apart from IP Restrictions, everything else work fine.

**Comment by larsnaesbye** [comment]
@javaChip56 Have you tried Konga 2 if it works as well?

**Comment by javaChip56** [comment]
@larsnaesbye I'm actually not aware that there already is a Konga 2. Mind if you can share the repo for that?

**Comment by larsnaesbye** [comment]
Sure. 
https://github.com/pantsel/konga2-ui
and
https://github.com/pantsel/konga2-server

I have not tried it myself.

**Comment by narinkaew** [comment]
I got an errors too (Kong 2.0.1 and Konga 0.14.7). I executed with docker image.

When create connection, got an error
![image](https://user-images.githubusercontent.com/16592840/76589061-6cacae80-651b-11ea-9040-b4ff00da5af3.png)

Then inspect, got the message
Error: got 503 response
503 Service Unavailable
Failed to connect to server localhost

I got response from "http://localhost:8001" properly
![image](https://user-images.githubusercontent.com/16592840/76589181-cf9e4580-651b-11ea-99d7-c4557ffbbb65.png)

Any suggest?

Thanks in advance
Narin

**Comment by javaChip56** [comment]
@larsnaesbye I will try to check that out. Although I'm quite surprised to see that there's a v2.0. I didn't even see a v1.0.

@narinkaew are both Konga and Kong running in their respective containers?
You may want to try using 172.17.0.1 instead of localhost to connect Konga to Kong.

**Comment by joehoeller** [comment]
I am having same isue:

![Screenshot from 2020-03-19 19-36-17](https://user-images.githubusercontent.com/5199900/77126995-eca1af80-6a18-11ea-904a-5f7096dbb7fc.png)

**Comment by joehoeller** [comment]
Also not sure if this matters, but on initial log in, there is no default connection: 
![Screenshot from 2020-03-19 19-47-08](https://user-images.githubusercontent.com/5199900/77127445-7e5dec80-6a1a-11ea-8d38-2a2c29e61f52.png)

**Comment by javaChip56** [comment]
@joehoeller are both Kong and Konga running in a docker container on the same host?

**Comment by narinkaew** [comment]
@javaChip56  Thanks for information but My Konga still can't connect to kong even though open browser with http://localhost:8001 is work perfectly.

Here is the new network name 'kong-net'
Network : kong-net
There are 3 container in the network
- kong-database (postgres), 172.24.0.2
- kong, 172.24.0.3
- konga, 172.24.0.4

![image](https://user-images.githubusercontent.com/16592840/77130325-0f1fe100-6a8a-11ea-9391-0db19938b21c.png)

I tried connect konga to kong with difference url but all can't connect. 

![image](https://user-images.githubusercontent.com/16592840/77130437-90777380-6a8a-11ea-94db-18f77d72a753.png)

Here is my docker-compose.yml
- Docker 19.03.8, build afacb8b
- Kong 2.0.1
- Konga 0.14.7

```
version: "3.7"

#volumes:
#  kong_data: {}
  
networks:
 kong-net:
    name: kong-net

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
      #POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    #volumes:
    #  - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:latest
    command: kong migrations up
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_PORT: 5432
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: always
    container_name: kong
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      #KONG_TRUSTED_IPS: 0.0.0.0/0,::/0
      #KONG_REAL_IP_RECURSIVE: "on"
    depends_on:
      - kong-database
      - kong-migration
    links:
      - "kong-database:kong-database"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga_db"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    networks:
        - kong-net   
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: konga_db
      KONGA_HOOK_TIMEOUT: 120000
      POOL_SIZE: 10
      #DB_URI: postgresql://kong:kong@kong-database:5432/konga_db
      NODE_ENV: production
    depends_on:
      - kong-database
      - kong
      - konga-prepare
    ports:
      - "1337:1337"
    links:
      - kong:kong
```
      
I'm trying to figure it out. 

Thanks in advance
