### ISSUE TITLE
BASE_URL doesn't works

### ISSUE THREAD

**Issue by searva** [pantsel/konga#629]
Hi,

I have seen other related issues about this topic but they were closed and comments have no helped me either. 

In my case I must lift Konga (latest -> 0.14.9) responding with a base path, because in production konga will be behind a proxy with path routing. I have tried to run konga with env variable BASE_URL=/konga/ but doesn't seems to works: all routes respond with 404 not found. 

Even with a local simple docker container runing as:

`docker run -d -p 8083:1337 -e "BASE_URL=/konga/" -e "NODE_ENV=production" -e "KONGA_LOG_LEVEL=silly" -e "DB_ADAPTER=postgres" -e "DB_HOST=ctti33" -e "DB_PORT=32054" -e "DB_DATABASE=konga" -e "DB_PG_SCHEMA=public" -e "DB_USER=admin" -e "DB_PASSWORD=admin123" --name konga  pantsel/konga` 

the result is the same:

for "http://localhost:8083/konga/" konga logs says:

`Disabling CSRF protection for /konga since request has no session.
Sending 404 ("Not Found") response
Disabling CSRF protection for /favicon.ico since request has no session.
Disabling CSRF protection for /konga/ since request has no session.
Sending 404 ("Not Found") response`

Any clue of what am I missing? Thank you in advance...

**Comment by SamWoodruf** [comment]
Were you able to come up with a solution? @searva

**Comment by wxy2wxh** [comment]
I am also facing the same problem.

**Comment by searva** [comment]
I didn't find a solution to this. I ended up mounting Konga on root path and Kong in /api :(

**Comment by tianqiuming** [comment]
我也有同样的问题，没有找到很好的解决办法，向大家求助。

**Comment by baiyun1102** [comment]
I am also facing the same problem.

**Comment by flaccid** [comment]
Unfortunate this project is not getting the love it needs. I'm also not seeing this env var being an option for the helm chart configmap where we can set it via a helm value. As a result I cannot do an ingress due to the 'everything being a 404` issue.

Here is the annotations I am using on the ingress:
```
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/target-type: ip
```

I'm guessing that this is what the app needs to work under a hostname, but I could be wrong. For now the only thing I can do is port-forward to the service or pod.
